# sparse version of csbm-5
name: csbm-7
val_size: 0.0
test_size: 0.2

n_nodes: 200
num_classes: 4
expected_degree: 2
edge_p_type: by_snr_and_degree
edge_p_snr: 3.0
feature_sigma: 1.0
feature_class_mean_distance: 0.5