version: 1
disable_existing_loggers: false

formatters:
  normal:
    format: "%(asctime)s [%(levelname)s] %(name)s:%(lineno)s | %(funcName)s | %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: normal
    stream: ext://sys.stdout

loggers:
  src:
    level: DEBUG
    handlers: [console]
    propagate: false

  root:
    level: DEBUG
    handlers: [console]
